### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by mark-summerfield** [jryannel/qt5-cadaques#10]
back-link: ch04/index.html#qml-syntax

You don't explain why it is a good idea to name the root element "root". Why not "app" or "application" or "window"?

You don't explain why the id name is unquoted but the color name is quoted when both are single words.

You show how to run qmlscene on Unix-like systems but not on Windows. Also, you don't explain why you are using qmlscene rather than some other exectuable.

**Comment by jryannel** [comment]
Made some changes to the section. I hope this works now better. Thanks. Added a reminder for myself for the windows case. Not sure how best to describe it.
