### ISSUE TITLE
Applying Animations

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#101]
typo: To organize the element …: we used a a Column positioner -> we used a Column positioner
typo: calculated the with and height -> calculated the width and height
typo: that the text is a wide as the -> that the text is as wide as the
typo: They need to travel all to to y=40 -> They need to travel all to y=40
typo: It’s starts immediately. -> It starts immediately.

The text says the y-position of the rockets is 205, while the code snippets say 200! 

back-link: ch05/index.html#applying-animations

**Comment by mschuette** [comment]
"When a rocket is clicked their y-position is reseted to 205": That doesn't correspond to the code snippit of rocket 1 and might be confusing for the reader.

typo: Here is does not have any effect -> Here it does not have any effect

"Here is does not have any effect as long as the animation is running, it event may disturb the rocket as it sets the y-position for a fraction of a section to a new y-position until the animation set’s it to the next value.": That sentence is not understandable to me and too long for one sentence.

typo: The 2nd rocket -> The second rocket
typo: and adapt is speed to -> and adapt its speed to
typo: The 3rd rocket -> The third rocket
typo: The 1st rocket -> The first rocket

**Comment by jryannel** [comment]
Thanks a lot. Hope this section is better now.
