### ISSUE TITLE
Use of numbers

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#102]
general: All numbers in text sections between 1 and 10 should be written as words (one, two, …), not numbers

**Comment by jryannel** [comment]
Can you remember where this was ch04 or ch05 and which text section? I struggle to find the exact location. Thanks

**Comment by mschuette** [comment]
It was in both chapters with several occurrences. 
E.g..
ch04: Simple Transformations: This follows a simple rule, after 3 times using the same code it’s better to extract a component.
ch05: Applying Animations: We exposed 2 properties: text and image source as 

But there are more. So it's a general hint.

## Marcel

Marcel Schuette
Professional Service Engineer
Nokia, Qt Development Frameworks

---

Von: ext jryannel [reply@reply.github.com]
Gesendet: Donnerstag, 31. Mai 2012 08:30
An: Schuette Marcel (Nokia-DXM/Munich)
Betreff: Re: [qt5-cadaques] Use of numbers (#102)

Can you remember where this was ch04 or ch05 and which text section? I struggle to find the exact location. Thanks

---

**Comment by jryannel** [comment]
Okay. Need to remember this. Thx
