### ISSUE TITLE
Easing Curves

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#105]
typo: all property changes where done -> all property changes were done
typo: with an linear easing type -> with a linear easing type (not 100% sure about that)
Animation should … . Animations should … : two sentence in a row start with the same words. not good.
"Here you can try some easing type": The "Here" refers to the image  and section below. Maybe it's better to say: In this section, you can see the usage of some … 
typo: For we added a -> For that we added a 
typo: and pay with it -> and play with it
typo: please observer the -> please observe the
general: The code example uses model data to assign an easing type to an animation. That is already quite complex stuff. Maybe it might be a good idea to have a very simple example in the first paragraph, which shows the use of easing types. You could refer to the documentation to see a complete list of available easing types. Maybe also the practical usage of easing types (like overshoot for more reality) could be expressed a little bit more in detail. 

back-link: ch05/index.html#easing-curves

**Comment by jryannel** [comment]
Added a short paragraph about easing parameters and where to find more information. Otherwise fixed the typos.
