### ISSUE TITLE
Grouped Animations

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#106]
Grouping can be in 2 way: -> Grouping can be done in two ways:
typo: animate it’s behavior. -> animate its behavior.
Let’s see: quite colloquially
(ROT1): should be same style (red) as X1, Y1, Y2
"The animation reaches it points ": Not sure, what that should mean.
typo: so wee need to encapsulate -> so we need to encapsulate
typo: we would like to ball to be -> we would like the ball to be
I use a`Easing.OutCirc` curve: I think a space is missing, so the system recognizes the style

back-link: ch05/index.html#grouped-animations

**Comment by jryannel** [comment]
Thanks. Fixed. A lot of little annoying "I should not make in the first place" mistakes:(
