### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#109]
(“*”” means any state).; to many ' at the end
"…and set the filter to filter only the switch es from “go” to “stop” state": sentence not understandable
typo: In site the transition -> Inside the transition
typo: the light are blinking -> the lights are blinking 
maybe you also -> . Maybe you also

back-link: ch05/index.html#transitions

**Comment by jryannel** [comment]
Thanks. I have mostly rewritten the paragraph. It was really a strange sentence.
