### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by bweimer** [jryannel/qt5-cadaques#12]
back-link: ch04/index.html#qml-syntax

s/QML is designed from the ground up to describe user interfaces not text-document./QML is designed from the ground up to describe user interfaces not text-documents./
"text-documents" (plural)

s/In general you always want to import QtQuick 2.0 as your default set as elements/In general you always want to import QtQuick 2.0 as your default set of elements/

Consistency: In the same list (above) either print a full stop at the end of each list element or remove it for each element.

**Comment by jryannel** [comment]
Thanks. Made the changes. And removed the "." at then end of the lists.
