### ISSUE TITLE
grammar / typo

### ISSUE THREAD

**Issue by bweimer** [jryannel/qt5-cadaques#13]
back-link: ch04/index.html#properties

s/A property has default a value and a well-defined type./A property has a default value and a well-defined type./

s%// (7) Keys is a attached property%// (7) KeyNavigation is an attached property%
btw, "focus: true" has nothing to do with attached properties, so it should be placed before the comment above.

**Comment by jryannel** [comment]
Thanks. Fixed this. Will upload the fix later today
