### ISSUE TITLE
name vs. type

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#14]
"An element is declared by it’s name followed by { }"

isn't it "type" or "name of the component" ... it's not the name of the element.
It's a minor perspective thing ... but I think "type" would be easier to understand

**Comment by jryannel** [comment]
Thanks, you are correct. Qt Documentation also uses type (http://qt-project.org/doc/qt-4.8/qdeclarativeintroduction.html) "Objects are specified by their type, followed by a pair of braces in between which additional data can be defined for the object, such as its property values and any child objects."
