### ISSUE TITLE
 it is used to reference elements inside a QML document. 

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#16]
actually that's wrong.
The  key word is dynamic scoping ... at powerful, dempting and extermly dangarous pattern which one can't turn off :(

To some extend your write: It's very important to only reference elements inside YOUR qml document, altough nobody forces you to.
This should be a "tip" or something

**Comment by jryannel** [comment]
Thanks added a warning to the topic. Don't use dynamic-scoping! Please leave the back-links in the comment field of the issues. It makes it easier for us to find the topic.
