### ISSUE TITLE
Particles from Shaders

### ISSUE THREAD

**Issue by andijakl** [jryannel/qt5-cadaques#169]
back-link: ch08/index.html#particle-simulations

There are many ready-made particle systems / properties available for shaders, and this is what most games would be using. Therefore, a chapter about particles should mention the possibilities there more (especially as it's a book and not the Qt docs) - how compatible is Qt, how to integrate particle system shaders, etc.

**Comment by jryannel** [comment]
We are not aware of the integration of other particle systems. I just know this one. Sorry little bit tunnel visioning here.
