### ISSUE TITLE
Downloadable pdf version ?

### ISSUE THREAD

**Issue by pasnox-intuisphere** [jryannel/qt5-cadaques#173]
back-link: index.html#a-book-about-qt5

Hi,

Is it possible to get a downloadable / pdf version of the book ?
Will be very fine to get it in another format like pdf, or better QtHelp format.

Regards,

**Comment by jryannel** [comment]
Both should be possible, but currently we focus on the online-version.

**Comment by jryannel** [comment]
A download version will come this month

**Comment by pasnox-intuisphere** [comment]
Great! thanks
