### ISSUE TITLE
Great work guys!

### ISSUE THREAD

**Issue by hardcodes** [jryannel/qt5-cadaques#179]
I'm misusing this to contact you because I didn't find a contact address after a quick swipe through the book.
Please provide a PDF version of this! It would be great if one could take it on the road, there isn't always an internet connection available.

BR.
Sven

**Comment by jryannel** [comment]
Thanks. We currently focus on the HTML only version. But it's completely understandable.

Duplicate of #173 . So I will close this.

**Comment by aissat** [comment]
It's great job

**Comment by jryannel** [comment]
A download version will come this month
