### ISSUE TITLE
grammar

### ISSUE THREAD

**Issue by zander** [jryannel/qt5-cadaques#181]
back-link: ch01/index.html#meet-qt-5

"extension for Qt Quick."
You sometimes write "Qt Quick" Sometimes "QtQuick". Pick one. ;)

"The usage patterns computer users changed "
missing "of" before "computer".

"mobile touch-based always connected screens."
missing comma before "always"

"Where as in the past Windows UI has dominated the world"
whereas is one word
missing "the" before Windows.

"and it lies more to provide a "
grammer is funny; maybe "is leans more towards providing".

"With Qt 4.8, the Qt 4 release is almost 7 years old. "
I think you meant to say something like; "The Qt4 series, with the 4.8 as the last release, is now more than 8 years old."

"Qt C++ - The highly portable enhanced c++ library"
Use uppsecase C for both usages of "C++".

" It is composed of tags called elements in QtQuick enclosed in curly brackets"
missing comma before "enclosed".

"Qt Quick is easily extend able"
extendable is one word.

**Comment by justinfx** [comment]
Pull Request: https://github.com/qmlbook/qmlbook/pull/4

This could be closed here, and migrated to the new repo which accepts merge requests.
