### ISSUE TITLE
        property alias anotherTimes: thisLabel.times

### ISSUE THREAD

**Issue by wuming123057** [jryannel/qt5-cadaques#194]
```
    // (4) custom property
    property int times: 24

    // (5) property alias
    property alias anotherTimes: thisLabel.times
```

Note:
 An alias reference must be specified as <id>, <id>.<property> or <id>.<value property>.<property>

Qt 5.2 +Qt creator 3.0 + msvc2012 update 4 +window 7sp1 bit

**Comment by jryannel** [comment]
Fixed
