### ISSUE TITLE
property alias anotherTimes: thisLabel.times

### ISSUE THREAD

**Issue by wuming123057** [jryannel/qt5-cadaques#195]
back-link: ch04/index.html#properties
        // (4) custom property
        property int times: 24

```
    // (5) property alias
    property alias anotherTimes: thisLabel.times
```

Note: 
 An alias reference must be specified as <id>, <id>.<property> or <id>.<value property>.<property>

**Comment by jryannel** [comment]
Changed the wording to make clear it can be a property of an object or the object itself.
