### ISSUE TITLE
1.2.1. Digesting an User Interface - root element paragraph repetition

### ISSUE THREAD

**Issue by budziq** [jryannel/qt5-cadaques#202]
back-link: ch01/index.html#meet-qt-5

Hi,

I have spotted that in second and third paragraphs of "1.2.1. Digesting an User Interface" section you have repeated statement about the root element of the .qml document. First declaring it to be "Rectangle" (which is inconsistent with the code example) and later in next paragraph stating it to be "Image" (which is correct). I guess that the "Rectangle" paragraph is an offshoot from previous version of the chapter.

Best Regards

**Comment by jryannel** [comment]
Indeed. The first version had a rectangle as a root element. To save some lines of code we changed it for the background image. Thanks for spotting.
