### ISSUE TITLE
A "300 x 300 pixel" mistak after the HelloWorld.qml

### ISSUE THREAD

**Issue by weiqiangdragonite** [jryannel/qt5-cadaques#211]
back-link: ch02/index.html#hello-world

Below the HelloWorld.qml code, one sentence said:
This code in particular show a rectangle of 300 x 300 pixel geometry with a centered text “Hello World”.

I find it is not 300 x 300 pixel, is 360 x 360 pixel. Just a little mistake, hope you will correct it. n_n

**Comment by justinfx** [comment]
This could be closed in favor of pull request: https://github.com/qmlbook/qmlbook/pull/3
