### ISSUE TITLE
 default value 

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#22]
There are 2 side to the phrase "default value" ... in in qml-space you should only use the second one:
1. type-default-value (closed possible in c++ would be default-contructor)
2. state-default-value ... the value you set in your qml file out-side of all states ... or better: for the default state.

As the second one is very important to understand if you want to become a qml-hero it's dangarouse to "flood" people with 1. ;)
Either remove all statments about it, or find another word for it ;)

back-link: ch04/index.html#properties

**Comment by senyk** [comment]
ah seams there is another word for 1.:
http://doc.qt.nokia.com/4.7-snapshot/propertybinding.html#default-properties

**Comment by jryannel** [comment]
I changed the default value mostly to initial value where it makes sense. It really avoids confusion. Thanks for bringing this up.

**Comment by jryannel** [comment]
Here my own thoughts about this:

Properties have initial values. A the default state named "" is defined by the initial values of the properties. QML uses the default keyword to mark properties to be used when no property name is given on the left-side of the binding for example Text { "Hello World" ), the string would be bound to the default property.
