### ISSUE TITLE
Reworded paragraph suggestions

### ISSUE THREAD

**Issue by Rolias** [jryannel/qt5-cadaques#241]
back-link: ch02/index.html#summary
# The original

> The HelloWord.qml is written in the QML language. We will discuss the QML language in more depth in the next chapter, just so much it’s describes the user interface in a series of hierarchical elements. This code in particular show a rectangle of 300 x 300 pixel geometry with a centered text “Hello World”. A mouse area spans the whole rectangle and when the user clicks it, the application quits.
# Suggested rewrite

HelloWorld.qml is written in the QML language. We will discuss the QML language in more depth in the next chapter. This example describes the user interface as a series of hierarchical elements. Specifically a 360 x 360 pixel rectangle with the centered text “Hello World”. A mouse area spans the whole rectangle and when the user clicks anywhere in the rectangle, the application quits.

**Comment by e8johan** [comment]
Fixed.
