### ISSUE TITLE
inconsistency root rectangle --> root image

### ISSUE THREAD

**Issue by serdaco** [jryannel/qt5-cadaques#244]
back-link: ch01/index.html#meet-qt-5

inconsistency, the samples show a root image
but the text in 'note 'talks about root rectangle

"Placing an image as a child element of our root rectangle element shows an important concept of a declarative language. You describe the user interface in the order of layers and grouping, where the topmost layer (our rectangle) "

**Comment by e8johan** [comment]
Fixed.

**Comment by serdaco** [comment]
Thanks, 
keep up the good work. 
Is the book coming out in paper form ?
