### ISSUE TITLE
Horizontal gradients

### ISSUE THREAD

**Issue by bweimer** [jryannel/qt5-cadaques#25]
back-link: ch04/index.html#rectangle-element

"Note 
It is not possible to create an angled gradient. For this it’s better to use premanufactured images"

Maybe also worth noting that horizontal gradients can be created by rotating the item by 90 degrees?

**Comment by jryannel** [comment]
From my perspective it's not really a solution as the rotation does not change the geometry of the object and thus the visible area will be different from the geometry and this will lead to confusion when laying out the element. I added this to the topic. Thanks for bringing this up.
