### ISSUE TITLE
Item and MouseArea -> no visual

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#26]
I wouldn't call Item and MouseArea visual.
They have a geometry, but that's it...

In detail:
a. QObject                                          non visual, no geometry
b. QDeclarativeItem default:             non visual, geometry
c. QDeclarativeItem with contents:          visual, geometry

The difference between b and c is, if this flag is set or not:
QGraphicsItem::ItemHasNoContents

back-link: ch04/index.html#item-element

**Comment by jryannel** [comment]
from qtdoc: "The Item is the most basic of all visual items in QML"  (http://doc.qt.nokia.com/4.7-snapshot/qml-item.html) as the mouse ara also derives from Item it can be used as a visual container enhanced with mouse input. Visual does more reflect it has geometry and not if it's paints anything. I will leave this.
