### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by bweimer** [jryannel/qt5-cadaques#28]
back-link: ch04/index.html#image-element

s/An image using PreserveAspectCrop should also to enable the clippping to avoid image data to be painted outside the Image element boundaries./An image using PreserveAspectCrop should also enable clippping to avoid image data to be painted outside the Image element boundaries./
(remove "to", possibly "the", as well?)

**Comment by jryannel** [comment]
Thanks. Merged the text with the note about clipping.
