### ISSUE TITLE
unexplained term HMI

### ISSUE THREAD

**Issue by jriddell** [jryannel/qt5-cadaques#284]
back-link: ch02/index.html#console-application

I've no idea what "HMI" means, maybe replace with "user interface"

**Comment by mozzbozz** [comment]
Human-Machine-Interface (see http://en.wikipedia.org/wiki/User_interface - there is a small remark about this term in the article) .

However, I also dislike the term and would prefer changing "graphical HMI" to GUI or whatever (a console application has a TUI (-> Text UI) which is also some sort of UI, so UI would not be sufficient).

**Comment by e8johan** [comment]
Fixed
