### ISSUE TITLE
chapters 1 to 3 typos

### ISSUE THREAD

**Issue by jriddell** [jryannel/qt5-cadaques#288]
back-link: index.html#a-book-about-qt5
patch attached

**Comment by jriddell** [comment]
http://starsky.19inch.net/~jr/tmp/qmlbook.diff

**Comment by e8johan** [comment]
As you've noticed, we've moved the repo to qmlbook/qmlbook. If this patch is still applicable, could you open an issue with it there? The link you provided does not seem to work right now.
