### ISSUE TITLE
spelling / english

### ISSUE THREAD

**Issue by bweimer** [jryannel/qt5-cadaques#30]
back-link: ch04/index.html#components

s/
There are different way to create components in QML./
There are different ways to create components in QML./
(way->ways)

s/
Our task is now to extract the button ui in a reusable component./
Now our task is to turn the button UI into a reusable component/ ??

s/
You do this by imagine how you would like to use the button./
To do so, consider how you would like to use the button./ ??

s/
Also I would expect the button has a sensible default size/
Also I would expect the button to have a sensible default size/ ?

s/
Additional we need to export the properties a user might want to change on the root level./
Additionally we need to export the properties a user might want to change on the root level./

s/
For this is important to now, out the root level properties can be accessed from outside this file./
It is important to know, that only root level properties can be accessed from outside a component file/ ??

s/
We will introduce more such ui components and also come back the button theme later./
We will introduce more such ui components and also come back to the button theme later./

**Comment by jryannel** [comment]
Thanks for spotting. Great!
