### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by mark-summerfield** [jryannel/qt5-cadaques#31]
back-link: ch04/index.html#rectangle-element

You should mention where the list of color names comes from. (Looks like rgb.txt to me.)

s/premanufactured/predefined/

**Comment by jryannel** [comment]
The colors are based on the SVG color names: http://www.w3.org/TR/css3-color/#svg-color. Need to mention this

**Comment by jryannel** [comment]
Thanks. Added a short note about color definitions.
