### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by mark-summerfield** [jryannel/qt5-cadaques#32]
back-link: ch04/index.html#text-element

You should mention wrapping and whether (and how) to set a background color.

**Comment by jryannel** [comment]
A background color can't be set on the text element, only the text and style color. A background color can only be set by providing an element which paints a background (e.g. a rectangle or image),

**Comment by jryannel** [comment]
Thanks for hinting about the background. It applies also later to the text-input element.
