### ISSUE TITLE
Hint to QDecalarativeImageProvider

### ISSUE THREAD

**Issue by wargand** [jryannel/qt5-cadaques#33]
back-link: ch04/index.html#image-element

Even if QDecalarativeImageProvider is not or is later explained, add at least a note here. It gave me quite a headache when I wanted to use an Image element with dynamically generated content and without having to write it somewhere in the filesystem. Would have been easier if I had at least know this class and what its purpose is at that time.

**Comment by jryannel** [comment]
Added a tip about this. Thanks
