### ISSUE TITLE
rectangle.qml or Rectangle.qml or main.qml

### ISSUE THREAD

**Issue by mariob** [jryannel/qt5-cadaques#37]
back-link: ch04/index.html#qml-syntax

The filename for the rectangle example is 'rectangle.qml'. The common practice for naming QML-component files is to use camel-case. If the rectangle example is intended to be used as a 'stand-alone' application I would recommend changing the name to main.qml (or something similar) to make it clear for the user that this is an application and not a component.

**Comment by jryannel** [comment]
In general you are correct, but we have a series of qml files in a chapter project. This why we use the lowercase convention and no main.qml file. The files should not (and cannot) be used as components. It's just a qml file which you can run. We should mention this somewhere in our conventions, which we don't have yet:-)
Won't change.
