### ISSUE TITLE
Almost whole 'Scripting' paragraph is incorrect

### ISSUE THREAD

**Issue by mariob** [jryannel/qt5-cadaques#39]
back-link: ch04/index.html#scripting
1. The text handler doesn't print the number of times the text has changed, it only prints the text.
   Maybe change 'text handler' to 'onTextChanged signal handler'
2. The text doesn't react on the escape key but the space key.
   You don't set the text from the js function, you update the spacesPressed property which will trigger the binding which updates the text
3. There's nothing in the example that will clear the text.

I think that you should highlight and elaborate on "The difference between QML : and JS = is, the binding is a contract and keeps true. The JS = is a one-time assignment.". It's a big difference between property binding and assignment.

**Comment by jryannel** [comment]
Thanks. I updated the source code example earlier and didn't update the text. Hmmm, lazy me. I added also a small discussion about binding and assignment and the possible conflicts.
