### ISSUE TITLE
Elaborate on Item element

### ISSUE THREAD

**Issue by mariob** [jryannel/qt5-cadaques#40]
back-link: ch04/index.html#item-element

I think you should elaborate a little bit more about the Item element.

Event though you have put the following statement at the end of the section, "An item has many fundamental properties, we will introduce most of them over the course of the book.", I still think you should list some properties because you mention geometry.

For example:
The Item doesn't do any painting by itself but has a lot of properties that is used to affect the visual appearance, among others, anchoring, geometry, rotation, scaling and opacity.

This makes it more clear that the Item actually have a lot of functionality for visual items.

**Comment by jryannel** [comment]
I added a table of the fundamental property groups and a short description for each of them. I think it's now better to understand for the reader. Thanks for the input.
