### ISSUE TITLE
z-order of Items

### ISSUE THREAD

**Issue by mariob** [jryannel/qt5-cadaques#43]
back-link: ch04/index.html#item-element

Probably you need to mention the natural and the z-order of Items.

For example, later in the chapter (Simple Transformations) you have a MouseArea as a background and three rockets that you can click. Why does this "just work" both graphics and click-wise.

**Comment by mariob** [comment]
Hmm, saw the note about "order of element in the document matters."

Should this be more highlighted than a note? If you're not interested in transforms for the moment when you read the book you'll completely miss out on this information.

**Comment by jryannel** [comment]
Maybe should be better described in the general item discussion. Close this and opened a new issue for a better Item description.
