### ISSUE TITLE
Always better to scale down

### ISSUE THREAD

**Issue by mariob** [jryannel/qt5-cadaques#44]
back-link: ch04/index.html#simple-transformations

"It’s always better to scale images down then up."

Should this be a side note? Could it also include an explanation why this is the case?

Also found a typo: s/then/than

**Comment by jryannel** [comment]
From my perspective scaling images up will always lead to scaling artifacts (e.g. blurred image). Whereas an scaled down image will stay crisp (using smooth:true). At least this is my understanding.
