### ISSUE TITLE
Positioners are a part of QtQuick and not QML

### ISSUE THREAD

**Issue by mariob** [jryannel/qt5-cadaques#45]
back-link: ch04/index.html#positioning-elements

These are called positioners and the following are provided in QML Row, Column, Grid and Flow.

Correct me if I'm wrong but aren't positioners actually a part of QtQuick and not QML?

BlackBerry cascades uses QML but doesn't have positioners, unfortunately  :)

**Comment by jryannel** [comment]
Correct. I think i mixed QML as the language and QtQuick as the default module several times.
