### ISSUE TITLE
Makes it sense to at leaset mention AnchorAnimation here?

### ISSUE THREAD

**Issue by wargand** [jryannel/qt5-cadaques#50]
back-link: ch05/index.html#animation-elements

I already noticed in the last chapter in the drag&drop note that you wrote you cannot drag an drop anchored elements, but did not say they can be 'unanchored' on-the-fly if necessary. Now you show all important animation elements, but again miss the AnchorAnimation. I am sure it will appear sooner or later, but why not put it into the list?

**Comment by jryannel** [comment]
Added anchors animation to the list of animations
