### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by bweimer** [jryannel/qt5-cadaques#51]
back-link: ch05/index.html#animations

s/
Each animation has a duration of 4000 milliseconds (msecs) and loops for infinite./
Each animation has a duration of 4000 milliseconds (msecs) and loops forever./ ?

s/
Both animations run in parallel and is started as soon as the UI is loaded./
Both animations run in parallel and are started as soon as the UI is loaded./

s/
No you can play around with the animation by changing [...]/
Now you can play around with the animation by changing [...]/

**Comment by jryannel** [comment]
Thanks. Alos fixed.
