### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by bweimer** [jryannel/qt5-cadaques#52]
back-link: ch05/index.html#applying-animations

s/
Later we see how animation can be used inside state transitions./
Later we see how animations can be used inside state transitions./

s/
To organize the element below the image we used a a Column positioner and calculated the with and height based on the columns childrenRect property./
To organize the element below the image we used a Column positioner and calculated the width and height based on the column's childrenRect property./
(remove one "a ", with->width, columns->column's)

s/
They need to travel all to to y=40./
They need to travel all to y=40./

s/
The first rocket travel using the animation on property. It’s starts immediately. When a rocket is clicked their y-position is reseted to 205. Here is does not have any effect as long as the animation is running, it event may disturb the rocket as it sets the y-position for a fraction of a section to a new y-position until the animation set’s it to the next value./

The first rocket travels using the animation on property. It starts immediately. When a rocket is clicked its y-position is reset to 205. Here it does not have any effect as long as the animation is running, it even may disturb the rocket as it sets the y-position for a fraction of a section to a new y-position until the animation sets it to the next value./

(travel->travels, It's->It, their->its, reseted->reset, is->it, event->even, set's->sets); "fraction of a section" - what?

**Comment by jryannel** [comment]
Thanks. Fixed
