### ISSUE TITLE
Good coding practices? States? JavaScript?

### ISSUE THREAD

**Issue by wargand** [jryannel/qt5-cadaques#54]
back-link: ch05/index.html#states-transitions

Perhaps this chapter is a good place to say something about good coding practices in QML? As far as I was able to see in other ppls. code many developers, who are used to code in C++ tend to do code in a way they are used to. Very often the same effect can be achieved using JavaScript functions or using states. Experienced C++ developers fall easily into the trap to write more of a JavaScript program, than a QML program.

**Comment by jryannel** [comment]
Added a note about QML vs JavaScript. Thanks
