### ISSUE TITLE
Tip section

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#58]
the logical flow is a little bit missing for me. It's more like a bullet point section. The single sentence don't build a logical sequence. 

back-link: ch04/index.html#qml-syntax

**Comment by mschuette** [comment]
More like:
Tip: Often you want to access a particular element by id or a parent element using the parent keyword. So it’s good practice to name your root element root using id: root.  Then you don't have to think about how the root element is named in your QML document when you give it the id root.

**Comment by jryannel** [comment]
Great. Took your sentence. Sounds much better.
