### ISSUE TITLE
first paragraph

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#61]
The first sentence might be a little bit more understandable, if examples for element name and properties would be given. Especially in a introduction chapter for people, you don't have so much experience with QML.
"A property is a simple key-value pair, e.g. width, height, color.". The example doesn't fit to the content of the sentence. You say, it's a pair, but only give a single name as example.

back-link: ch04/index.html#properties

**Comment by jryannel** [comment]
Added more explicit example for key-value pairs.
