### ISSUE TITLE
components section

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#73]
This shall be enough for the moment: second sentence in a row starts with "this". maybe also remove the sentence at all, as it is a little bit colloquially 

create .. create: "To create this we create ..." -> To achieve this, we create ...

mixture of "I" and "We". should be always I or we.

"For this is important to now, out the root level properties ...": not understandable, what it means 

"Sure there is more to this, but currently this is enough to keep us going.": quite colloquially

create a hole series -> create a whole series

back-link: ch04/index.html#components

**Comment by mschuette** [comment]
"There are different way to create components in QML." : What are the others?

**Comment by jryannel** [comment]
This was a lengthy one. Great feedback.
