### ISSUE TITLE
Positioning Elements

### ISSUE THREAD

**Issue by mschuette** [jryannel/qt5-cadaques#75]
In other sections, first the code snippit and the the output image was shown, here it's the other way round

The Grid element ...: in a grid, By setting -> in a grid, by setting 

In the simples case a model -> In the simplest case a model

We define our own colors property, -> We define our own color property,; name the new property for better recognition

As noted earlier JavaScript (EcmaScript): first occurrence of EcmaScript; should be mentioned in the Scripting section 

back-link: ch04/index.html#positioning-elements

**Comment by jryannel** [comment]
Thx. Fixed. Abou the images, I guess Johan and I need to sit down later to align all chapters.
