### ISSUE TITLE
The first example

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#79]
This is a very bad example.
It's not very good practice to use the "to" in "property bounded"-animation
(aka. "on"-animations ... I've no clue what the name for those is)

Those animations are used as:
"i've something sets the new value, how should it be animated"
not as:
"i've something sts the new value, i'll go somewhere else anyway"

There are reasons for using "to" on those, but those a for advance animations/programmers

back-link: ch05/index.html#animations

**Comment by jryannel** [comment]
Hmm, can't follow your argumentation. It's at least an easy example. The properties animated are not supposed to be set from outside at all.
