### ISSUE TITLE
English

### ISSUE THREAD

**Issue by mark-summerfield** [jryannel/qt5-cadaques#8]
back-link: ch04/index.html#quick-starter

s/an overview about QML/an overview of QML/
s/Later we will have a short look onto how to/Later briefly look at how to/
s/arrange lements/arrange elements/
s/look onto elements/look at elements/

I won't repeat suggestions that are the same to save us all time. 
Suggestion: g/look onto/look at/

**Comment by jryannel** [comment]
Thanks. Fixed. Will upload the changes later today.
