### ISSUE TITLE
Animation on property - runs when element is loaded

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#80]
This is wrong. It's "runs when property is 'changed' or 'set to a new value'

back-link: ch05/index.html#applying-animations

**Comment by senyk** [comment]
p.s.: Behavior on property  is very similar (not sure why there are both ... but they are applied/used/triggered very similar...
I think "Behavior on" is for complex animations, "Animation on" for simple ones

**Comment by senyk** [comment]
I think I found the real difference:
http://doc-snapshot.qt-project.org/5.0/qml-qtquick2-behavior.html
It has a "enabled" property ... so you can turn off the Behavior-Animation.
I would remove all "Behavior" from this chapter and go back to those in a later chapter.
It's definitely confusing (even for me) and doesn't add much at this point

**Comment by jryannel** [comment]
Added a sentence about the enabled property. Otherwise I fixed the other items.
