### ISSUE TITLE
several ways

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#81]
I would put "transition" in the list and just add a comment that this will be covered later.
Also there is a 4. way: binding

NumberAnimation {
running: something.someValue
}

This is not really covered by "standalone" because it's the "better" ... or declarative-way of standalone.
This is especially useful for cases where the user-input is in control of properties (e.g. ListView is moving)

... I would but it in the list and also add a "will be covered later"-comment. (you need to cover it eventually)

back-link: ch05/index.html#applying-animations

**Comment by jryannel** [comment]
I added the running case to the standalone animation. It can be triggered by running or start(). Still need to cover the running case. So I don't close this yet

**Comment by jryannel** [comment]
Added a running note and a note about the inverse geometry-dependency and being carefully about.
