### ISSUE TITLE
width: container.childrenRect.width; height: container.childrenRect.height

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#82]
Isn't that forcing the width and height?
Normally it should be vice versa: child's bound to it's parent to get there geometry.
... but i guess this is could be consider coding-style ;)

Anyway, I would keep it as simple as possible ... even if this means something isn't 100% declared

back-link: ch05/index.html#applying-animations

**Comment by senyk** [comment]
Ah ... I know the solution:
Remove the "Item" and use your Column as your root element.
You'll save a shit-load of useless lines and make stuff simpler

**Comment by senyk** [comment]
Ah wait ... the MouseArea can't be the a child of Column I guess?
Maybe get rid of the Column then :D

**Comment by jryannel** [comment]
MouseArea is an item and can't be a child of the column correct. The parent is depending of the child elements it's quit common for positioners to inverse the geometry dependency. I will check again but couldn't find a better and simpler solution. Also as I said in an earlier chapter I like to have an Item as the root element to export only a minimal API.

Won't fix
