### ISSUE TITLE
interpolation

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#86]
I would somewhere add the word interpolation :)
Because that's what you control when using the Easing properties.

e.g.:
"Till now as we haven't specified any easing attributes all property changes where done with an linear easing type."
change to:
"Till now as we haven't specified any easing attributes, which means the <default/init/fall-back/what ever> easing-curve Easing.Linear is used. Easing.Linear will result in a linear interpolation. In our example where x is animated from 0 to 240 in 4 seconds, this would mean that after 1 seconds the value will be 60, after 1 seconds it will be 120, and so on."

(Not sure about the exact chose of words ... but this sounds easier (at least in my brain))

btw.: I don't really like this sentence:
"For example an animation which changes the property x from initial 0 to 240 in 4 seconds will linear change to 240."
It's a bit confusing ;)

back-link: ch05/index.html#easing-curves

**Comment by jryannel** [comment]
I added a short example fo a plot, where the y-axis is the property and the x-axis is the time and the interpolation would be a straight line. Something like this. Thanks. Fixed
