### ISSUE TITLE
cursor blinks

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#89]
"Animation should be designed as the eye reacts very sensible on moving objects. Animations should support the UI in their flow. That’s the reason why a cursor blinks, a steady cursor is difficult to identify."

The one has little to do with the other ;)
The first is mainly eye-candy (which must be pleasing and fitting, right!) ... the second is a "permanent"-highlighter :)

(I know what you're meaning .. "eye reacts on moving objects"+"blinking cursor" => attention
... but it's a bit irritating to add such an example into a fluid-UI book ;)

back-link: ch05/index.html#easing-curves

**Comment by jryannel** [comment]
Thanks. Removed the not very lucky comparison of the cursor. And changed the text to point out animations define the interpolation curve for property changes. Closed
