### ISSUE TITLE
which act as an animation containers for other animation elements.

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#91]
Either tell them that SequentialAnimation and ParallelAnimation are derived from Animation as well 
e.g. "They are Animations themselves and therefor can be used exactly as such"

or you could, to this sentence:
"which act as an animation containers for other animation elements..."
add:
"...and for other group animations"

I would choose the first :)

back-link: ch05/index.html#grouped-animations

**Comment by jryannel** [comment]
Thanks. Fixed
