### ISSUE TITLE
When the system is switched on it goes automatically into the stop mode as default state.

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#94]
To understand states it's extremely important to understand "default state" and "default property"

This is the right place to explain it.
This is the wrong place to mix things up ;) 
... It doesn't go into "stop mode as default state"!
... "stop" is not the default state!
"" is the default state! ;)

If you're accepting this issue and change it so you're explaining "default property"/"default state",
just use the "default state" ("")  as off-state ("the traffic light is turned off")

And also remove the redundant:
 PropertyChanges { target: light2; color: "black" }
... and explain why you don't set this value for the "stop"-state.

back-link: ch05/index.html#states

**Comment by jryannel** [comment]
Thanks for the valuable and precise suggestions. I made sure people understand better the difference between initial valus and default state.
