### ISSUE TITLE
The default transition filter (from:”*”, to:”*”) are applied to any state switch (“*”” means any state).

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#95]
Again "default" ;) hehehe

I would phrase it like that:
You can also use the wild-cast "_" which means "any state". So for example (from:”_”, to:”*”) means from any state to any other state. By the way this is the default value for "from" and "to". 

maybe in addition:    So be careful if you're not setting "from" and "to"

back-link: ch05/index.html#transitions

**Comment by jryannel** [comment]
Used your sentence (halfway). Thanks
