### ISSUE TITLE
State { when: ... }

### ISSUE THREAD

**Issue by senyk** [jryannel/qt5-cadaques#96]
This is missing.
http://doc-snapshot.qt-project.org/5.0/qml-qtquick2-state.html#when-prop

Also default state is missing.
Maybe more ;)

I would do a separate "States and Transitions" chapter

back-link: ch05/index.html#states

**Comment by jryannel** [comment]
Added a note about the when property. I think states and transitions belongs together as there is no transitions without a state. Or did I miss something.
